# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

#==========================  Modules configuration =============================
filebeat.modules:

#---------------------------- Elasticsearch Module ----------------------------
- module: elasticsearch
  # Server log
  server:
    enabled: false
    
#=========================== Filebeat inputs =============================

# List of inputs to fetch data.
filebeat.inputs:

#------------------------------ Log input --------------------------------
- type: log

  # Change to true to enable this input configuration.
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.inputs:
  enabled: true
  path: /usr/local/sof-elk/lib/filebeat_inputs/*.yml

#========================== Elasticsearch output ===============================
output.logstash:
  enabled: true
  #hosts: ["${LOGSTASH_HOST}:5044"]
  hosts: ["logstash:5044"]
  ssl.enabled: false

#output.elasticsearch:
  #hosts: ["elasticsearch:9200"]

#============================== Dashboards =====================================
setup.dashboards.enabled: true
setup.dashboards.directory: /usr/local/sof-elk/kibana

#============================== Kibana =========================================
setup.kibana:
host: "kibana:5601"
ssl.enabled: false
   
#host: "${KIBANA_HOST}:5601"
#module: kibana
#host: "kibana:5601"

#============================== Xpack Monitoring ===============================
# xpack.monitoring:
#   enabled: true
#   elasticsearch: